### ISSUE TITLE
有个小需求，看是否已实现。开屏广告定制

### ISSUE THREAD

**Issue by bigtotorouk** [nullptrX/pangle_flutter#10]
开屏广告，我想在底部加上自己品牌logo。（很常见的那种）

**Comment by deeeev** [comment]
暂时不知道怎么去实现，有什么想法吗？

**Comment by bigtotorouk** [comment]
开屏广告提供一个widget。 不知道行不行。类似banner广告那样

**Comment by nullptrX** [comment]
可以做，但是开屏现在express类型的广告，宽高不成比例，图片会被压变形的

**Comment by nullptrX** [comment]
这个我试了，不会变形，可以用Widget实现一下。后续更新。 @bigtotorouk
