### ISSUE TITLE
banner广告渲染过慢。 且一次不能加多个banner

### ISSUE THREAD

**Issue by bigtotorouk** [nullptrX/pangle_flutter#11]
希望banner广告可以左右滑动。 我看有的插件是这个样子的

**Comment by deeeev** [comment]
受限于穿山甲SDK，广告是可以设置是否自动滚动的，自己好像不能手动滑动，并且间隔不低于30秒。所以就没有提供参数配置。
渲染速度问题，暂时不知道原因。有什么发现，欢迎在这里更新。

**Comment by bigtotorouk** [comment]
banner广告显示实在太慢了 。 ios勉强可以 。安卓一般界面打开5s才显示 。
