### ISSUE TITLE
大佬什么时候更新啊？

### ISSUE THREAD

**Issue by xinkong2000** [nullptrX/pangle_flutter#13]
现在碰见两个问题，不知道是不是我代码写的问题，还是插件不完善。
1，开屏广告，无法自定义isExpress: true时，开屏就不显示了；
2，信息流竖版视频广告，加载的数量多了以后，性能上有些问题。

**Comment by nullptrX** [comment]
1. 官方还没有express类型的开屏广告
2. 这种类型就是很耗性能的
本周周末会修复一些bug

**Comment by xinkong2000** [comment]
大佬，升级后报错啊，大致是抽象类或是接口有错误

**Comment by nullptrX** [comment]
升级sdk  `open_ad_sdk 3.3.0.0`
