### ISSUE TITLE
你好，信息流广告显示有些问题。

### ISSUE THREAD

**Issue by bigtotorouk** [nullptrX/pangle_flutter#14]
现在信息流广告都是个性化的模板。 我试了下，显示不成功。
我测试发现，信息流的广告id可以获取成功，但是feedview显示不出来。
下面是错误信息，这个错误信息是界面返回的时候提示的（没显示成功，穿山甲sdk也更新到最新的）。  最后是显示广告代码,  请指教

.io/pangle_feedview_2), stack: #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
I/flutter (19919): <asynchronous suspension>
I/flutter (19919): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
I/flutter (19919): #2      FeedViewController.remove (package:pangle_flutter/src/feed_view.dart:232:20)
I/flutter (19919): #3      FeedViewState._remove (package:pangle_flutter/src/feed_view.dart:143:18)
I/flutter (19919): #4      FeedViewState.dispose (package:pangle_flutter/src/feed_view.dart:73:5)
I/flutter (19919): #5      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4773:12)
I/flutter (19919): #6      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1935:13)
I/flutter (19919): #7      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
I/flutter (19919): #8      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
I/flutter (19919): #9      _InactiveEl
I/flutter (19919): interceptors

class FeedSimpleAdWidget extends StatefulWidget {
  @override
  _FeedSimpleAdWidgetState createState() => _FeedSimpleAdWidgetState();
}

class _FeedSimpleAdWidgetState extends State<FeedSimpleAdWidget> {
  bool removed = false;

  Future<String> _loadFeedData() async {
    print("feedad_id begin");
    PangleAd feedAd = await pangle.loadFeedAd(
      iOS: IOSFeedConfig(
        slotId: "xxxxxx",
        isExpress: true,
        imgSize: PangleImgSize.feed228_150,
        // slotId: kFeedId,
        count: 3,
        expressSize: PangleExpressSize(width: 375, height: 126)
      ),
      android: AndroidFeedConfig(
        slotId: "xxxxxxxxx",
        isExpress: true,
        imgSize: PangleImgSize.feed228_150,
        count: 3,
        expressSize: PangleExpressSize(width: 375, height: 126)
      ),
    );
    final feedAdDatas = feedAd.data;
    print("feedad_id ${feedAdDatas[0]}");
    return Future.value(feedAdDatas[0]);
  }

  @override
  Widget build(BuildContext context) {
    Size size = MediaQuery.of(context).size;
    double adWidth = (size.width-8*2.0);
    double adHeight = (adWidth*0.336);
    return Container(
      child: removed
          ? Container()
          : FutureBuilder(
              future: _loadFeedData(),
              builder: (BuildContext context, AsyncSnapshot<dynamic> snapshot) {
                print("feedad future build ${snapshot.data}");
                if (snapshot.connectionState == ConnectionState.done &&
                    !snapshot.hasError) {
                  return Container(
                    width: adWidth,
                    height: adHeight,
                    child: FeedView(
                      id: "${snapshot.data}",
                      isExpress: false,
                      onRemove: () {
                        setState(() {
                          removed = true;
                        });
                      },
                    ),
                  );
                } else {
                  if(snapshot.hasError){
                    print("Error : ${snapshot.error}");
                  }
                  return Container();
                }
              },
            ),
    );
  }
}

**Comment by nullptrX** [comment]
堆栈信息是不是没有复制完全

**Comment by nullptrX** [comment]
退出的问题发现了，感谢。不显示的问题看看有没有日志喃。

**Comment by bigtotorouk** [comment]
@nullptrX  不知道是不是这个，其他的没发现啥log

 [ERROR:flutter/shell/common/shell.cc(209)] Dart Error: Unhandled exception:
E/flutter (23722): MissingPluginException(No implementation found for method remove on channel nullptrx.github.io/pangle_feedview_2)
E/flutter (23722): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
E/flutter (23722): <asynchronous suspension>
E/flutter (23722): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter (23722): #2      FeedViewController.remove (package:pangle_flutter/src/feed_view.dart:232:20)
E/flutter (23722): #3      FeedViewState._remove (package:pangle_flutter/src/feed_view.dart:143:18)
E/flutter (23722): #4      FeedViewState.dispose (package:pangle_flutter/src/feed_view.dart:73:5)
E/flutter (23722): #5      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4773:12)
E/flutter (23722): #6      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1935:13)
E/flutter (23722): #7      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
E/flutter (23722): #8      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
E/flutter (23722): #9      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
E/flutter (23722): #10     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
E/flutter (23722): #11     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1944:25)
E/flutter (23722): #12     BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2754:27)
E/flutter (23722): #13     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2558:15)
E/flutter (23722): #14     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2753:7)
E/flutter (23722): #15     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:868:18)
E/flutter (23722): #16     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
E/flutter (23722): #17     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
E/flutter (23722): #18     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
E/flutter (23722): #19     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:865:7)
E/flutter (23722): #20     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (23722): #21     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (23722): #22     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (23722): #23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by nullptrX** [comment]
嗯  这个是刚刚那个问题的日志

**Comment by bigtotorouk** [comment]
这个问题，结局了 。 可以关闭了

**Comment by daima1122** [comment]
> 这个问题，结局了 。 可以关闭了

怎么解决的，老哥
