### ISSUE TITLE
信息流广告显示有问题

### ISSUE THREAD

**Issue by bigtotorouk** [nullptrX/pangle_flutter#16]
界面中信息流广告显示正常，但是弹出软键盘之后，信息流广告就小时了，软键盘消失，广告也不会显示出来。

**Comment by nullptrX** [comment]
@bigtotorouk 贴一下测试用例，注意activity的configChanges是否按照[Flutter范例](https://flutter.cn/docs/development/add-to-app/android/add-flutter-screen#step-1-use-a-theme-with-translucency)配置
```xml

android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"

```
