### ISSUE TITLE
0.0.6版本 loadInterstitialAd 调此方法 报错 Unhandled Exception: UnimplementedError

### ISSUE THREAD

**Issue by wumingman** [nullptrX/pangle_flutter#2]
![image](https://user-images.githubusercontent.com/17715408/89978697-b6531e00-dca0-11ea-9cf7-cecf01b807ba.png)

PanglePlugin 类中 我标红的地方是不是该去掉？

![image](https://user-images.githubusercontent.com/17715408/89978866-13e76a80-dca1-11ea-94f1-89f829964163.png)

**Comment by nullptrX** [comment]
这个版本还没实现，用`0.1.1`简单实现了一下
