### ISSUE TITLE
1.0.0版本profile&release模式报错

### ISSUE THREAD

**Issue by xiangzy1** [nullptrX/pangle_flutter#21]
Android resource linking failed                                    
build/pangle_flutter/intermediates/packaged_res/profile/drawable/pangle_flutter_placeholder.xml:8: AAPT: error: resource drawable/tt_playable_l_logo (aka :drawable/tt_playable_l_logo) not found.
                                                                        
build/pangle_flutter/intermediates/packaged_res/profile/drawable-xxhdpi-v4/pangle_flutter_bg_placeholder.xml:4: AAPT: error: resource color/tt_cancle_bg (aka :color/tt_cancle_bg) not found.

**Comment by nullptrX** [comment]
你是不是混淆掉了？

**Comment by nullptrX** [comment]
如果不是混淆问题，那可能是你没有导入SDK，`1.0.0`不会自己依赖sdk了

[如何配置](https://github.com/nullptrX/pangle_flutter/blob/master/SETUP.md#1-%E5%AF%BC%E5%85%A5%E4%BE%9D%E8%B5%96)

**Comment by xiangzy1** [comment]
之前用的0.9.1 也自己引入了sdk，也试了新的引入
混淆的话我把minifyEnabled改成false 把proguardFiles配置删除了还是报这个错

创建了一个新的flutter2.0.3的项目，引入1.0.0，用maven导入，release报了个不一样的错误(debug正常)
`Could not determine the dependencies of task ':compileReleaseAidl'.
> Failed to query the value of task ':compileReleaseAidl' property 'aidlFrameworkProvider'.
   > SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '.../.pub-cache/hosted/pub.flutter-io.cn/pangle_flutter-1.0.0/android/local.properties'.`

**Comment by nullptrX** [comment]
maven要用我的仓库 

上面报的错不是我的项目问题，是你的项目没有找到安卓的SDK位置。

**Comment by nullptrX** [comment]
发现是项目遗留文件删除不干净导致的。后面我会测试打包了。

**Comment by xiangzy1** [comment]
辛苦大佬

**Comment by nullptrX** [comment]
> pangle_flutter: ^1.0.1
