### ISSUE TITLE
Android Global

### ISSUE THREAD

**Issue by iptodays** [nullptrX/pangle_flutter#22]
能否支持Android 海外流量

**Comment by nullptrX** [comment]
Android版本，穿山甲没有海外的SDK吧？

**Comment by iptodays** [comment]
其实是有的，，， 只是需要申请
![image](https://user-images.githubusercontent.com/15830996/112660330-4a6ca100-8e90-11eb-9a16-2e38b51cbb85.png)

**Comment by nullptrX** [comment]
嗯 刚去看了  但是我没有SDK  不知道如何适配

**Comment by nullptrX** [comment]
![img](https://cdn.jsdelivr.net/gh/nullptrX/assets/images/20210327000751.png)

**Comment by iptodays** [comment]
因为我对安卓不太熟悉，感觉好麻烦

**Comment by nullptrX** [comment]
应该差不多吧  你如果有SDK  直接依赖我的模块  再导入海外的SDK  看看能不能用就晓得了

**Comment by iptodays** [comment]
海外版没有下载的那块逻辑，好像比国内的权限也要少
![image](https://user-images.githubusercontent.com/15830996/112660960-fb733b80-8e90-11eb-80d2-141ff74430d6.png)

**Comment by nullptrX** [comment]
哦  那还是容易吧 你把我仓库拿去  哪里报错删哪里就行了

**Comment by iptodays** [comment]
👌  我试试  OK之后给你反馈

**Comment by nullptrX** [comment]
行

**Comment by iptodays** [comment]
https://cowtransfer.com/s/df5636fef2f845
这是官方demo

**Comment by nullptrX** [comment]
我跑了一下 都没有获取到广告  怎么看效果呢

**Comment by iptodays** [comment]
我这边跑是有广告的  应该得挂代理

**Comment by iptodays** [comment]
我可以加你好友  需要什么资料的话 我发你

**Comment by nullptrX** [comment]
行  用什么联系方式

**Comment by iptodays** [comment]
qq 739814184
wx nowiizvv

**Comment by nullptrX** [comment]
加了 晚点交流
