### ISSUE TITLE
激励视频的回调方法调用。

### ISSUE THREAD

**Issue by woodcode** [nullptrX/pangle_flutter#25]
**激励视频的回调方法如何调用？**

我运行了例子，没能找到如何判断激励视频播放是否播放成功或者关闭的回调方法，是不是还没实现这些回调吗？

**Comment by nullptrX** [comment]
返回的`PangleResult`中`verify`，`true`是播放成功后关闭的结果，反之则是播放未完成关闭的结果。
如果你想通过回调获取详细的状态回调，那我这边没有这样实现。

![](https://cdn.jsdelivr.net/gh/nullptrX/assets/images/20210408094931.png)

**Comment by woodcode** [comment]
非常感谢您的回复。

主要是这样的场景，超过30秒的激励视频，看了下穿山甲文档说看到27秒就可以获得激励， 用户可以选择关闭。
按您的方法，例如：50秒的视频，用户看了30秒后关闭，是获得不到激励奖励的吧？

**Comment by nullptrX** [comment]
是可以获取的。我在`onRewardVerify`回调时获取`verify`值，在`onAdClose`回调时返回`verify`结果。

之前我在`onRewardVerify`返回结果，Flutter这边收到回调后弹吐司或者对话框会被视频界面盖住。所以才放到`onAdClose`回调结果。
