### ISSUE TITLE
open_ad_sdk.3.2.6.7-union 编译出现错误

### ISSUE THREAD

**Issue by heshengyahuai** [nullptrX/pangle_flutter#26]
**用 build.gradle 导入依赖 dependencies**
    implementation group: 'com.bytedance.ttgame', name: 'open_ad_sdk', version: '3.2.6.7-union'
这是 maven 仓库查询到的最新版。

不知道是不是因为没有用对版本...编译出现错误

**Expected behavior**
Running Gradle task 'assembleDebug'...
e: /android/src/main/cn/io/github/nullptrx/pangleflutter/delegate/FLTInterstitialExpressAd.kt: (31, 3): 'onShow' overrides nothing
e: /android/src/main/cn/io/github/nullptrx/pangleflutter/delegate/FLTRewardedVideoAd.kt: (56, 10): Class 'RewardAdInteractionImpl' is not abstract and does not implement abstract member public abstract fun onRewardVerify(p0: Boolean, p1: Int, p2: String!): Unit defined in com.bytedance.sdk.openadsdk.TTRewardVideoAd.RewardAdInteractionListener
e: /android/src/main/cn/io/github/nullptrx/pangleflutter/delegate/FLTRewardedVideoAd.kt: (60, 3): 'onRewardVerify' overrides nothing
e: /android/src/main/cn/io/github/nullptrx/pangleflutter/view/FlutterBannerView.kt: (113, 3): 'onShow' overrides nothing
e: /android/src/main/cn/io/github/nullptrx/pangleflutter/view/FlutterFeedView.kt: (85, 3): 'onShow' overrides nothing
pangle_flutter: cn

FAILURE: Build failed with an exception.

**Flutter:**
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

**Comment by nullptrX** [comment]
看文档，Android版本适配的3.5+。国内使用的话，maven上的库走不通的，那是国外使用的。

**Comment by heshengyahuai** [comment]
> 看文档，Android版本适配的3.5+。国内使用的话，maven上的库走不通的，那是国外使用的。

确实用错了。多谢！
