### ISSUE TITLE
在点击全屏广告观看时点击广告下方的查看详情会上报崩溃信息

### ISSUE THREAD

**Issue by zhancheng** [nullptrX/pangle_flutter#27]
在点击全屏广告观看时点击广告下方的查看详情会上报崩溃信息，具体信息如下：
isLuBanLandingPage error java.lang.NullPointerException: Attempt to invoke virtual method 'int org.json.JSONObject.optInt(java.lang.String)' on a null object reference

![image](https://user-images.githubusercontent.com/2122947/115494888-1622af80-a299-11eb-9ce8-6e9afd20257f.png)

 Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.7 19H524 darwin-x64, locale zh-Hans-CN)

**Comment by nullptrX** [comment]
这是穿山甲sdk报的错，对使用有影响吗？

**Comment by zhancheng** [comment]
@nullptrX 对使用没有影响 但是对崩溃统计有影响 有此问题引发了大量的崩溃日志~

**Comment by nullptrX** [comment]
最近比较忙  没时间维护  你先排查看看  过几天我试试

**Comment by zhancheng** [comment]
@nullptrX 好的 多谢
