### ISSUE TITLE
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.

### ISSUE THREAD

**Issue by SinoMiles** [nullptrX/pangle_flutter#28]
试了好几个穿山甲插件都是报这个错误。
![image](https://user-images.githubusercontent.com/9588025/116245505-9a929800-a79b-11eb-9668-13e485818afc.png)

https://github.com/jhomlala/betterplayer/issues/100

播放器作者的回复是插件使用了太低的compileSdkVersion（如果单独使用播放器插件是没任何问题的，集成穿山甲就会报错）

**Comment by nullptrX** [comment]
上面不是说sdk.dir没有定义吗

**Comment by SinoMiles** [comment]
@nullptrX  但是我单独使用better player的话就没问题。只要使用穿山甲就会这样。

**Comment by nullptrX** [comment]
`local.properties`，android项目根目录下。
