### ISSUE TITLE
信息流广告显示不全，获取广告数字段count设置无效

### ISSUE THREAD

**Issue by wumingman** [nullptrX/pangle_flutter#3]
![image](https://user-images.githubusercontent.com/17715408/90000232-7b61e200-dcc2-11ea-8eaf-1e31ab009c6f.png)

**Comment by nullptrX** [comment]
你好，这个问题是因为我在返回高度的时候写死的大概的高度，晚上我会优化一下。

**Comment by nullptrX** [comment]
返回3条数据的问题，我也试过。暂时也不清楚为什么只返回3条，但是那个字段先保留了，因为他们sdk可以传这个值。具体数据还是看返回的结果。

**Comment by nullptrX** [comment]
宽高现已经通过计算而来，试试最新版本。

**Comment by wumingman** [comment]
用你的demo运行起来看效果没问题了，但我这边用自己的FeedId显示不出来，日志也没打印什么，

![image](https://user-images.githubusercontent.com/17715408/90203720-0b637100-de14-11ea-93bd-21d705b47313.png)

我这边所有的广告位都只能创建个性化广告位 

![image](https://user-images.githubusercontent.com/17715408/90203984-ca1f9100-de14-11ea-8766-4736c060e45f.png)

**Comment by nullptrX** [comment]
宽高问题已解决，字段count无效问题与sdk无关

模版渲染支持问题（Duplicate of # 5）
