### ISSUE TITLE
Cannot access built-in declaration 'kotlin.collections.MutableMap'. Ensure that you have a dependency on the Kotlin standard library

### ISSUE THREAD

**Issue by SinoMiles** [nullptrX/pangle_flutter#31]
直接引入插件运行就会报错了！看样子需要配置kotlin,这个需要在项目哪里配置吗？

pangle_flutter: ^1.1.0

![image](https://user-images.githubusercontent.com/9588025/117190746-6447bf00-ae12-11eb-984c-9dac3d14f553.png)

![image](https://user-images.githubusercontent.com/9588025/117191209-e20bca80-ae12-11eb-82dc-8f5589df0930.png)

![image](https://user-images.githubusercontent.com/9588025/117192294-1d5ac900-ae14-11eb-807f-9d63f7264dc3.png)

**Comment by jacobguan** [comment]
同问

**Comment by SinoMiles** [comment]
@nullptrX

**Comment by SinoMiles** [comment]
@jacobguan  哥们 你解决没

**Comment by nullptrX** [comment]
如果是kotlin的问题，把我的库fork一下，把[build.gradle#76](https://github.com/nullptrX/pangle_flutter/blob/master/android/build.gradle#L76)取消注释就好了，是我以为不用引入这个库导致的。

**Comment by nullptrX** [comment]
@SinoMiles @jacobguan

**Comment by SinoMiles** [comment]
e: C:\Users\Administrator\AppData\Local\Pub\Cache\git\pangle_flutter-295663a206211802dbbc2617c96cf5e78aca2d81\android\src\main\cn\io\github\nullptrx\pangleflutter\PangleAdManager.kt: (81, 21): Unresolved reference: removeFirst
e: C:\Users\Administrator\AppData\Local\Pub\Cache\git\pangle_flutter-295663a206211802dbbc2617c96cf5e78aca2d81\android\src\main\cn\io\github\nullptrx\pangleflutter\PangleAdManager.kt: (103, 21): Unresolved reference: removeFirst
e: C:\Users\Administrator\AppData\Local\Pub\Cache\git\pangle_flutter-295663a206211802dbbc2617c96cf5e78aca2d81\android\src\main\cn\io\github\nullptrx\pangleflutter\delegate\FLTInterstitialExpressAd.kt: (10, 1): Class 'FLTInterstitialExpressAd' is not abstract and does not implement abstract member public abstract fun onSelected(p0: Int, p1: String!, p2: Boolean): Unit defined in com.bytedance.sdk.openadsdk.TTAdDislike.DislikeInteractionCallback
e: C:\Users\Administrator\AppData\Local\Pub\Cache\git\pangle_flutter-295663a206211802dbbc2617c96cf5e78aca2d81\android\src\main\cn\io\github\nullptrx\pangleflutter\delegate\FLTInterstitialExpressAd.kt: (34, 3): 'onSelected' overrides nothing
e: C:\Users\Administrator\AppData\Local\Pub\Cache\git\pangle_flutter-295663a206211802dbbc2617c96cf5e78aca2d81\android\src\main\cn\io\github\nullptrx\pangleflutter\delegate\FLTInterstitialExpressAd.kt: (41, 3): 'onRefuse' overrides nothing
e: C:\Users\Administrator\AppData\Local\Pub\Cache\git\pangle_flutter-295663a206211802dbbc2617c96cf5e78aca2d81\android\src\main\cn\io\github\nullptrx\pangleflutter\view\FlutterBannerView.kt: (20, 1): Class 'FlutterBannerView' is not abstract and does not implement abstract member public abstract fun onSelected(p0: Int, p1: String!, p2: Boolean): Unit defined in com.bytedance.sdk.openadsdk.TTAdDislike.DislikeInteractionCallback
e: C:\Users\Administrator\AppData\Local\Pub\Cache\git\pangle_flutter-295663a206211802dbbc2617c96cf5e78aca2d81\android\src\main\cn\io\github\nullptrx\pangleflutter\view\FlutterBannerView.kt: (117, 3): 'onSelected' overrides nothing
e: C:\Users\Administrator\AppData\Local\Pub\Cache\git\pangle_flutter-295663a206211802dbbc2617c96cf5e78aca2d81\android\src\main\cn\io\github\nullptrx\pangleflutter\view\FlutterBannerView.kt: (125, 3): 'onRefuse' overrides nothing
e: C:\Users\Administrator\AppData\Local\Pub\Cache\git\pangle_flutter-295663a206211802dbbc2617c96cf5e78aca2d81\android\src\main\cn\io\github\nullptrx\pangleflutter\view\FlutterFeedView.kt: (19, 1): Class 'FlutterFeedView' is not abstract and does not implement abstract member public abstract fun onSelected(p0: Int, p1: String!, p2: Boolean): Unit defined in com.bytedance.sdk.openadsdk.TTAdDislike.DislikeInteractionCallback
e: C:\Users\Administrator\AppData\Local\Pub\Cache\git\pangle_flutter-295663a206211802dbbc2617c96cf5e78aca2d81\android\src\main\cn\io\github\nullptrx\pangleflutter\view\FlutterFeedView.kt: (88, 3): 'onSelected' overrides nothing
e: C:\Users\Administrator\AppData\Local\Pub\Cache\git\pangle_flutter-295663a206211802dbbc2617c96cf5e78aca2d81\android\src\main\cn\io\github\nullptrx\pangleflutter\view\FlutterFeedView.kt: (95, 3): 'onRefuse' overrides nothing

@nullptrX 现在用的是fork修改以后的版本，还是有一些错误运行不起来。

**Comment by nullptrX** [comment]
这个是你用的穿山甲sdk跟我适配的版本不兼容，你用对应的sdk或者根据错误信息先实现一下

**Comment by zeewell** [comment]
> Unresolved reference: removeFirst

后来解决了吗？你现在使用的SDK是什么版本？有问题吗？
