### ISSUE TITLE
Project with path ':open_ad_sdk' could not be found in project ':pangle_flutter'.

### ISSUE THREAD

**Issue by sinacn546** [nullptrX/pangle_flutter#33]
> 方式二：
从穿山甲3.5.0.6版本开始，开发者也可以使用Gradle依赖导入穿山甲SDK

使用这种方式引入后，插件在打包时会报
> Project with path ':open_ad_sdk' could not be found in project ':pangle_flutter'.

**Comment by nullptrX** [comment]
这个好像需要你自己导入sdk
