### ISSUE TITLE
腾讯shadow 加载flutter混编打包的插件 

### ISSUE THREAD

**Issue by longrenzhut** [nullptrX/pangle_flutter#35]
腾讯shadow 加载flutter混编打包的插件 ，有没有遇到aseets图片都显示不不出来的问题，有时间能不能回答下，我的微信15088765390

**Comment by nullptrX** [comment]
我这里不是shadow项目，你应该提到shadow去。

**Comment by longrenzhut** [comment]
大佬，你没有遇到，毕竟你也集成了shadow，在shadow 还需要去fork，谢谢大佬求指导

**Comment by nullptrX** [comment]
你去新建一个项目，写个demo，然后留下链接，在你的项目里面讨论。

**Comment by longrenzhut** [comment]
嗯嗯
