### ISSUE TITLE
Android3.8.0.0无法运行

### ISSUE THREAD

**Issue by daima1122** [nullptrX/pangle_flutter#39]
**Describe the bug**
Android3.8.0.0无法运行

e: E:\flutter\.pub-cache\hosted\pub.dartlang.org\pangle_flutter-1.2.0\android\src\main\cn\io\github\nullptrx\pangleflutter\PangleAdManager.kt: (6, 8): Unresolved reference: com
e: E:\flutter\.pub-cache\hosted\pub.dartlang.org\pangle_flutter-1.2.0\android\src\main\cn\io\github\nullptrx\pangleflutter\PangleAdManager.kt: (7, 8): Unresolved reference: com
e: E:\flutter\.pub-cache\hosted\pub.dartlang.org\pangle_flutter-1.2.0\android\src\main\cn\io\github\nullptrx\pangleflutter\PangleAdManager.kt: (8, 8): Unresolved reference: com
e: E:\flutter\.pub-cache\hosted\pub.dartlang.org\pangle_flutter-1.2.0\android\src\main\cn\io\github\nullptrx\pangleflutter\PangleAdManager.kt: (9, 8): Unresolved reference: com
e: E:\flutter\.pub-cache\hosted\pub.dartlang.org\pangle_flutter-1.2.0\android\src\main\cn\io\github\nullptrx\pangleflutter\PangleAdManager.kt: (10, 8): Unresolved reference: com
e: E:\flutter\.pub-cache\hosted\pub.dartlang.org\pangle_flutter-1.2.0\android\src\main\cn\io\github\nullptrx\pangleflutter\PangleAdManager.kt: (11, 8): Unresolved reference: com
e: E:\flutter\.pub-cache\hosted\pub.dartlang.org\pangle_flutter-1.2.0\android\src\main\cn\io\github\nullptrx\pangleflutter\PangleAdManager.kt: (12, 8): Unresolved reference: com
e: E:\flutter\.pub-cache\hosted\pub.dartlang.org\pangle_flutter-1.2.0\android\src\main\cn\io\github\nullptrx\pangleflutter\PangleAdManager.kt: (13, 8): Unresolved reference: com
e: E:\flutter\.pub-cache\hosted\pub.dartlang.org\pangle_flutter-1.2.0\android\src\main\cn\io\github\nullptrx\pangleflutter\PangleAdManager.kt: (14, 8): Unresolved reference: com
e: E:\flutter\.pub-cache\hosted\pub.dartlang.org\pangle_flutter-1.2.0\android\src\main\cn\io\github\nullptrx\pangleflutter\PangleAdManager.kt: (15, 8): Unresolved reference: com
e: E:\flutter\.pub-cache\hosted\pub.dartlang.org\pangle_flutter-1.2.0\android\src\main\cn\io\github\nullptrx\pangleflutter\PangleAdManager.kt: (16, 8): Unresolved reference: com
e: E:\flutter\.pub-cache\hosted\pub.dartlang.org\pangle_flutter-1.2.0\android\src\main\cn\io\github\nullptrx\pangleflutter\PangleAdManager.kt: (38, 49): Not enough information to infer type variable V
e: E:\flutter\.pub-cache\hosted\pub.dartlang.org\pangle_flutter-1.2.0\android\src\main\cn\io\github\nullptrx\pangleflutter\PangleAdManager.kt: (38, 86): Unresolved reference: TTNativeExpressAd
e: E:\flutter\.pub-cache\hosted\pub.dartlang.org\pangle_flutter-1.2.0\android\src\main\cn\io\github\nullptrx\pangleflutter\PangleAdManager.kt: (39, 98): Unresolved reference: TTRewardVideoAd
e: E:\flutter\.pub-cache\hosted\pub.dartlang.org\pangle_flutter-1.2.0\android\src\main\cn\io\github\nullptrx\pangleflutter\PangleAdManager.kt: (40, 100): Unresolved reference: TTFullScreenVideoAd
e: E:\flutter\.pub-cache\hosted\pub.dartlang.org\pangle_flutter-1.2.0\android\src\main\cn\io\github\nullptrx\pangleflutter\PangleAdManager.kt: (42, 37): Unresolved reference: TTAdManager
e: E:\flutter\.pub-cache\hosted\pub.dartlang.org\pangle_flutter-1.2.0\android\src\main\cn\io\github\nullptrx\pangleflutter\PangleAdManager.kt: (43, 27): Unresolved reference: TTAdNative
e: E:\flutter\.pub-cache\hosted\pub.dartlang.org\pangle_flutter-1.2

Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (6 weeks ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1

Android 3.8.0.0 
pangle_flutter: ^1.2.0

**Comment by nullptrX** [comment]
你导入sdk了吗

**Comment by nullptrX** [comment]
缺少信息，如果有新的信息可再开启。
