### ISSUE TITLE
支持模版渲染Banner

### ISSUE THREAD

**Issue by wumingman** [nullptrX/pangle_flutter#4]
日志打印 ：D/BannerAdManager( 5831): 媒体在平台上申请的代码位“是否原生”属性与代码中使用的接口不匹配。例如：1. 媒体在平台上选择的是个性化模板banner广告的话，Android代码中请参考BannerExpressActivity进行调用；iOS代码中请参考BUDExpressBannerViewController进行调用。2. 媒体在平台上选择的是个性化模板插屏广告的话，代码中请参考InteractionExpressActivity进行调用；iOS代码位中请参考BUDExpressInterstitialViewController进行调用。
PS：模板广告会带有express字样标识。 40022

![image](https://user-images.githubusercontent.com/17715408/90103463-2337e800-dd75-11ea-868b-629a4191d714.png)
我在穿山甲后台，只能创建这种bannerId,没得选其他形式的BannerId

**Comment by nullptrX** [comment]
你好，这个广告位还没实现。你那边急吗？

**Comment by wumingman** [comment]
现在穿山甲后台只能创建我这种FeedId，你用的这种怎么创建的，我这边用哪种广告位都行？能教我怎么创建么？是不是穿山甲官方废弃了你那种信息流广告位？------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Nikola&amp;nbsp;X&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月13日(星期四) 下午5:52
收件人:&nbsp;&quot;nullptrX/pangle_flutter&quot;<pangle_flutter@noreply.github.com&gt;;
抄送:&nbsp;&quot;wumingman&quot;<1006329824@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nullptrX/pangle_flutter] 自己创建的广告位id 显示不出来 (#4)

**Comment by nullptrX** [comment]
你创建的不是banner广告位吗，怎么又是信息流了呢？穿山甲sdk加载banner的另一个接口就是你这种广告位，可能每个广告主可以申请的广告位不同吧

**Comment by nullptrX** [comment]
新版本已支持模版渲染，再试试。
```dart

dependencies:
    pangle_flutter: ^0.1.2

```

**Comment by wumingman** [comment]
> 新版本已支持模版渲染，再试试。
> 
> ```dart
> dependencies:
>     pangle_flutter: ^0.1.2
> ```

自己创建的BannerId可以显示出来了，但是FeedId 自己创建的还是显示不出来，发现个新问题，移除BannerView 还是 退出页面 都会报如下错误，但不影响使用 

![image](https://user-images.githubusercontent.com/17715408/90201608-ef5cd100-de0d-11ea-890e-353d1f16c018.png)

**Comment by nullptrX** [comment]
信息流广告也有模版渲染吗，这个还没实现。这个错误应该是个bug，我调试看看。
