### ISSUE TITLE
安卓上激励视频没返回

### ISSUE THREAD

**Issue by chenchat** [nullptrX/pangle_flutter#40]
插件版本: 1.1.0
问题代码如下：
CCHud.show();
        PangleResult result = await pangle.loadRewardedVideoAd(
          iOS: IOSRewardedVideoConfig(slotId: "xxx"),
          android: AndroidRewardedVideoConfig(slotId: "xxx"),
        );
        CCHud.dismiss();

问题描述
在安卓上，pangle.loadRewardedVideoAd这个方法一直没有返回，概率挺大的。所以会导致我这边的hud一直在显示。
iOS没这个问题。

**Comment by nullptrX** [comment]
我这边已测试过没有问题。你要确定是你没有隐藏掉还是我没有回调导致的。

**Comment by chenchat** [comment]
> 我这边已测试过没有问题。你要确定是你没有隐藏掉还是我没有回调导致的。
> 
> 我使用的版本是：
> pangle_flutter: ^1.2.0
> open_ad_sdk: 3.8.0.0
> 
> 你使用的版本需要对应匹配
> pangle_flutter: ^1.1.0
> open_ad_sdk: 3.5.0.0+

你好，我这边版本是对的，开屏、banner都是可以正常显示的，这个激励视频有时也是正常显示的，出发的场景是安卓上，当后台（穿山甲）没有激励广告时，才会触发，如果穿山甲有激励视频正常返回则没问题。

至于 1.2.0版本，我尝试升级了一下，编译报错，好像和1.1.0集成方式不一样？所以没有升级了。

**Comment by nullptrX** [comment]
广告sdk每个版本接口都有些变动  建议你fork源码  自行适配你手上的sdk版本

**Comment by nullptrX** [comment]
@chenchat 你这边还会重现吗？有没有找到具体问题
