### ISSUE TITLE
引入pangle_flutter: 1.2.0报如下错误

### ISSUE THREAD

**Issue by sinacn546** [nullptrX/pangle_flutter#41]
```
Running Gradle task 'assembleDebug'...
e: D:\app\flutter2.2.1\.pub-cache\hosted\pub.flutter-io.cn\pangle_flutter-1.2.0\android\src\main\cn\io\github\nullptrx\pangleflutter\delegate\FLTFullScreenVideoAd.kt: (54, 3): 'onFullScreenVideoCached' overrides nothing
e: D:\app\flutter2.2.1\.pub-cache\hosted\pub.flutter-io.cn\pangle_flutter-1.2.0\android\src\main\cn\io\github\nullptrx\pangleflutter\delegate\FLTRewardedVideoAd.kt: (32, 3): 'onRewardVideoCached' overrides nothing
pangle_flutter: cn

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pangle_flutter:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 20s
Exception: Gradle task assembleDebug failed with exit code 1

```

环境信息：
Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (7 weeks ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1

pangle_flutter: 1.2.0

**Comment by nullptrX** [comment]
open_ad_sdk版本使用3.8.0.0+

**Comment by sinacn546** [comment]
之前一直尝试的是官网添加仓库引入依赖的方式，依赖版本是3.8.0.3，
版本满足了条件但还是报了提问中的错误。

现在改为导入3.8.0.3版本jar包的方式，出现以下错误：

`Running Gradle task 'assembleDebug'...
D:\project\test\android\app\src\debug\AndroidManifest.xml:47:13-51 Error:
	Attribute activity#com.bytedance.sdk.openadsdk.activity.base.TTWebPageActivity@theme value=(@style/tt_landing_page) from [:open_ad_sdk:] AndroidManifest.xml:47:13-51
	is also present at [com.pangle.cn:ads-sdk:3.6.1.8] AndroidManifest.xml:52:13-50 value=(@style/tt_full_screen).
	Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml:43:9-48:57 to override.
D:\project\test\android\app\src\debug\AndroidManifest.xml:54:13-51 Error:
	Attribute activity#com.bytedance.sdk.openadsdk.activity.base.TTMiddlePageActivity@theme value=(@style/tt_landing_page) from [:open_ad_sdk:] AndroidManifest.xml:54:13-51
	is also present at [com.pangle.cn:ads-sdk:3.6.1.8] AndroidManifest.xml:59:13-50 value=(@style/tt_full_screen).
	Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml:49:9-55:57 to override.
D:\project\test\android\app\src\debug\AndroidManifest.xml:60:13-51 Error:
	Attribute activity#com.bytedance.sdk.openadsdk.activity.base.TTPlayableWebPageActivity@theme value=(@style/tt_landing_page) from [:open_ad_sdk:] AndroidManifest.xml:60:13-51
	is also present at [com.pangle.cn:ads-sdk:3.6.1.8] AndroidManifest.xml:65:13-50 value=(@style/tt_full_screen).
	Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml:56:9-61:57 to override.
D:\project\test\android\app\src\debug\AndroidManifest.xml:66:13-51 Error:
	Attribute activity#com.bytedance.sdk.openadsdk.activity.base.TTVideoWebPageActivity@theme value=(@style/tt_landing_page) from [:open_ad_sdk:] AndroidManifest.xml:66:13-51
	is also present at [com.pangle.cn:ads-sdk:3.6.1.8] AndroidManifest.xml:71:13-50 value=(@style/tt_full_screen).
	Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml:62:9-67:57 to override.
D:\project\test\android\app\src\debug\AndroidManifest.xml:72:13-51 Error:
	Attribute activity#com.bytedance.sdk.openadsdk.activity.base.TTVideoScrollWebPageActivity@theme value=(@style/tt_landing_page) from [:open_ad_sdk:] AndroidManifest.xml:72:13-51
	is also present at [com.pangle.cn:ads-sdk:3.6.1.8] AndroidManifest.xml:77:13-50 value=(@style/tt_full_screen).
	Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml:68:9-73:57 to override.
D:\project\test\android\app\src\debug\AndroidManifest.xml:78:13-51 Error:
	Attribute activity#com.bytedance.sdk.openadsdk.dislike.TTDislikeWebViewActivity@theme value=(@style/tt_landing_page) from [:open_ad_sdk:] AndroidManifest.xml:78:13-51
	is also present at [com.pangle.cn:ads-sdk:3.6.1.8] AndroidManifest.xml:83:13-50 value=(@style/tt_full_screen).
	Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml:74:9-79:57 to override.
pangle_flutter: cn

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
Exception: Gradle task assembleDebug failed with exit code 1`

**Comment by sinacn546** [comment]
但是在初始化时
```
  await pangle.init(
    iOS: IOSConfig(appId: kAppId),
    android: AndroidConfig(appId: kAppId),
  );
```
报了如下错误
```
E/MethodChannel#nullptrx.github.io/pangle(30223): Failed to handle method call
E/MethodChannel#nullptrx.github.io/pangle(30223): java.lang.RuntimeException: Please use asyn init!
E/MethodChannel#nullptrx.github.io/pangle(30223): 	at com.bytedance.sdk.openadsdk.api.d.g.init(TTPluginSdkInitializer.java:49)
E/MethodChannel#nullptrx.github.io/pangle(30223): 	at com.bytedance.sdk.openadsdk.TTAdSdk.init(TTAdSdk.java:52)
E/MethodChannel#nullptrx.github.io/pangle(30223): 	at io.github.nullptrx.pangleflutter.PangleAdManager.initialize(PangleAdManager.kt:246)
E/MethodChannel#nullptrx.github.io/pangle(30223): 	at io.github.nullptrx.pangleflutter.PangleFlutterPluginImpl.onMethodCall(PangleFlutterPluginImpl.kt:133)
E/MethodChannel#nullptrx.github.io/pangle(30223): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#nullptrx.github.io/pangle(30223): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#nullptrx.github.io/pangle(30223): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#nullptrx.github.io/pangle(30223): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#nullptrx.github.io/pangle(30223): 	at android.os.MessageQueue.next(MessageQueue.java:363)
E/MethodChannel#nullptrx.github.io/pangle(30223): 	at android.os.Looper.loop(Looper.java:176)
E/MethodChannel#nullptrx.github.io/pangle(30223): 	at android.app.ActivityThread.main(ActivityThread.java:8349)
E/MethodChannel#nullptrx.github.io/pangle(30223): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#nullptrx.github.io/pangle(30223): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/MethodChannel#nullptrx.github.io/pangle(30223): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
E/flutter (30223): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, Please use asyn init!, null, java.lang.RuntimeException: Please use asyn init!
E/flutter (30223): 	at com.bytedance.sdk.openadsdk.api.d.g.init(TTPluginSdkInitializer.java:49)
E/flutter (30223): 	at com.bytedance.sdk.openadsdk.TTAdSdk.init(TTAdSdk.java:52)
E/flutter (30223): 	at io.github.nullptrx.pangleflutter.PangleAdManager.initialize(PangleAdManager.kt:246)
E/flutter (30223): 	at io.github.nullptrx.pangleflutter.PangleFlutterPluginImpl.onMethodCall(PangleFlutterPluginImpl.kt:133)
E/flutter (30223): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (30223): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (30223): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter (30223): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (30223): 	at android.os.MessageQueue.next(MessageQueue.java:363)
E/flutter (30223): 	at android.os.Looper.loop(Looper.java:176)
E/flutter (30223): 	at android.app.ActivityThread.main(ActivityThread.java:8349)
E/flutter (30223): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (30223): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/flutter (30223): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
E/flutter (30223): )
E/flutter (30223): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
E/flutter (30223): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter (30223): <asynchronous suspension>
E/flutter (30223): #2      PanglePlugin.init (package:pangle_flutter/src/pangle_plugin.dart:139:7)
E/flutter (30223): <asynchronous suspension>
E/flutter (30223): #3      main (package:test/main.dart:26:3)
E/flutter (30223): <asynchronous suspension>
E/flutter (30223): 
```

**Comment by nullptrX** [comment]
```log
java.lang.RuntimeException: Please use asyn init!
```

android初始化配置那儿传入参数asyncInit(true)

[此处加上配置](https://github.com/nullptrX/pangle_flutter/blob/master/android/src/main/cn/io/github/nullptrx/pangleflutter/PangleAdManager.kt#L173)
```kotlin
asyncInit(true)
```

好像默认就是async的，我这边并不需要配置的。不知道你那边是什么情况。

**Comment by sinacn546** [comment]
使用了你最新提交的代码，并在173行插入了asyncInit(true)
```
    asyncInit(true)
    var titleBarTheme: Int? = null
    if (titleBarThemeIndex != null) {
      titleBarTheme = PangleTitleBarTheme.values()[titleBarThemeIndex].value
    }
```
还是报上面的错误

> java.lang.RuntimeException: Please use asyn init!

Null Safety之前的最后一个版本0.10.1是引入成功过的，升级到1.2.0就不成功了

**Comment by nullptrX** [comment]
用我的demo会出现这个问题吗？

**Comment by nullptrX** [comment]
`pangle_flutter: ^1.3.0` 已适配新的初始化方法
