### ISSUE TITLE
建议将穿山甲Android SDK打包进package，免得出现版本不一致而导致的各类问题。

### ISSUE THREAD

**Issue by zeewell** [nullptrX/pangle_flutter#43]
建议将穿山甲Android SDK打包进插件，免得出现版本不一致而导致的各类问题。

如果 穿山甲Android SDK 有版本更新，就bump一个新版本来适配。

没有经过太多思考，可能方向有误，仅供参考。

**Comment by nullptrX** [comment]
插件之前没办法带入aar哦，现在可以了吗

**Comment by nullptrX** [comment]
`pangle_flutter: ^1.3.0` 已内置android sdk.
