### ISSUE TITLE
iOS引入1.3.0问题

### ISSUE THREAD

**Issue by wulaosan33** [nullptrX/pangle_flutter#44]
在打开app注册时报
You need to replace the BUAdSDK.bundle file with the 3.8.1.0 version 
此时ads-cn的BUAdSDK.bundle 的version已经是3.8.1.0了。

example没有这样的问题。

**Flutter:**
 - version 2.0.6

**Comment by nullptrX** [comment]
清除缓存后再编译试试.  `flutter clean`

**Comment by wulaosan33** [comment]
解决了
