### ISSUE TITLE
激励视频如果显示的是小说类型的广告，点X就会闪退

### ISSUE THREAD

**Issue by SinoMiles** [nullptrX/pangle_flutter#45]
![image](https://user-images.githubusercontent.com/9588025/128980902-7e9b2701-7ceb-4028-915a-32cc3f392953.png)

如果激励视频是这种小说广告的话 点击右上角X号或者看完视频以后就会闪退。由于这种广告类型很少所以很难测试到具体报错。

**Comment by nullptrX** [comment]
哪个版本的？

**Comment by SinoMiles** [comment]
安卓 3.5. 你那个3.8的一直有问题啊 提示.removefirst未找到。所以我安卓一直还是用的3.5

**Comment by nullptrX** [comment]
removefirst是因为你的kotlin版本低了

**Comment by nullptrX** [comment]
android 3.5 不是我的版本，要说我插件的版本。

**Comment by SinoMiles** [comment]
我之前提交了一个pull request 有个参数转换报错。所以我是直接fork的你最新版本然后自己修改了那个转换那里。另外这个版本用安卓3.8的sdk运行不起来，3.5就可以。

**Comment by nullptrX** [comment]
你那个参数问题  不是那么改的  我已经改过了  另外你说这个版本 是哪个版本？

**Comment by SinoMiles** [comment]
就是你现在仓储的版本。我是直接同步的你的代码然后在项目里使用的。

**Comment by nullptrX** [comment]
这个版本已经用的3.9.0.0了  运行不起来的话  可以贴错误上来撒  我都不知道你想问什么  麻烦按模板提issue
