### ISSUE TITLE
The plugins `pangle_flutter` use a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by YaoShuwei** [nullptrX/pangle_flutter#46]
**1.简述问题**
升级到flutter 2.5.0之后，运行pub get或调试应用时，提示标题内容

**2.重现步骤**
pub get ，调试应用

**3.期望结果**
不显示此提示

**4.SDK版本:**
 - flutter: 2.5.0
 - dart: 2.14.0
 - pangle_flutter: 1.4.1
 - android:
 - iOS:

**额外信息**
无

**Comment by nullptrX** [comment]
已修复

**Comment by YaoShuwei** [comment]
> 已修复

好快，作者辛苦了
