### ISSUE TITLE
申请支持 gromore sdk

### ISSUE THREAD

**Issue by BokAugust** [nullptrX/pangle_flutter#47]
**1.简述需求**
现在穿山甲好像已经大量提供 gromore 接入了，看了我们几个平台小号（没什么量的）都已经开通了gromore 权限，聚合 sdk 对于开发者来说应该能有更多选择，十分期待 pangle_flutter 可以跟进支持 gromore sdk。

**2.解决方案**

一如既往支持。

**Comment by nullptrX** [comment]
我这边还没有申请GroMore资格，方便给个demo我先看看吗？

**Comment by zeewell** [comment]
> 我先看看

关注～～

**Comment by zeewell** [comment]
这个feature会有计划吗？ @nullptrX

**Comment by nullptrX** [comment]
考虑到维护时间成本，目前是做不了的。有能力的可以参考本项目实现。

**Comment by zeewell** [comment]
理解。试试招募些人，共同维护。
