### ISSUE TITLE
点击事件穿透到BannerView问题

### ISSUE THREAD

**Issue by zeewell** [nullptrX/pangle_flutter#48]
如果有Flutter Widget 在 BannerView 上面，点击该 Flutter Widget 时，BannerView也会收到点击事情并打开相应的广告。请问此问题是个BUG还是应该如何解决呢？

谢谢！

--- 

iOS上存在，Android没有测试。

```
➜  ~ flutter --version
Flutter 2.5.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4cc385b4b8 (8 days ago) • 2021-09-07 23:01:49 -0700
Engine • revision f0826da7ef
Tools • Dart 2.14.0
```

pangle版本：v1.4.4 但好像这几个版本都有这个问题。
最近两个flutter稳定版本都一样，更早的没有测试。

**Comment by nullptrX** [comment]
你没有看文档吧  [Banner](https://github.com/nullptrX/pangle_flutter#4-banner%E5%B9%BF%E5%91%8A)

**Comment by zeewell** [comment]
哈哈，我晚上测试看看 ||-_-

**Comment by zeewell** [comment]
忘记更新了，问题解决。

但还有个建议，是否可以把点击（或不可点击）区域的参数改成广告内部的相对位置？

这样在广告的位置是可以变化时，处理起来会简单很多。

比如下图，我这里的例子（显示于页面底部），上拉可以显示更多消息，广告也会跟着往上移动。这个时候，右上解自定义的覆盖区域要不可点击，就需要重新设置区域位置参数。
![IMG_2084](https://user-images.githubusercontent.com/1610404/133919352-bd630639-227e-490d-82b5-eb46697b37d3.jpg)

**Comment by nullptrX** [comment]
暂时不能，这个是原生View，监听不了你界面的滚动。我demo给了滚动的方案，你可以先用着。有更好的解决方案，欢迎提供。

**Comment by nullptrX** [comment]
已使用最新方案处理点击穿透问题，详情见[FLTView](https://github.com/nullptrX/pangle_flutter/blob/master/ios/Classes/FLTView.swift)
