### ISSUE TITLE
build 失败  Suggestion: add 'tools:replace="android:allowBackup"'

### ISSUE THREAD

**Issue by letterl** [nullptrX/pangle_flutter#49]
**1.简述问题**
根据文档添加xml的参数后
启动失败
在gradle build时
G:\code\appA\android\app\src\debug\AndroidManifest.xml:17:13-40 Error:
	Attribute application@allowBackup value=(false) from AndroidManifest.xml:17:13-40
	is also present at [com.pangle.cn:ads-sdk:3.9.0.5] AndroidManifest.xml:37:9-35 value=(true).
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:8:5-56 to override.

**2.重现步骤**

**3.期望结果**

**4.SDK版本:**
 - flutter:2.5.1
 - dart:
 - pangle_flutter: ^1.4.4
 - android:30
 - iOS:

**额外信息**
无

**Comment by nullptrX** [comment]
`Suggestion: add 'tools:replace="android:allowBackup"' to element at AndroidManifest.xml:8:5-56 to override.`

**Comment by nullptrX** [comment]
善用翻译软件

**Comment by letterl** [comment]
> `Suggestion: add 'tools:replace="android:allowBackup"' to element at AndroidManifest.xml:8:5-56 to override.`

1，看得懂
2，添加就会引发其他错误
3，放弃使用了 可以关闭这个了
