### ISSUE TITLE
支持各类型个性化模板渲染广告

### ISSUE THREAD

**Issue by wumingman** [nullptrX/pangle_flutter#5]
![image](https://user-images.githubusercontent.com/17715408/90207068-ea048400-de17-11ea-82fb-8312e56c7d43.png)
![image](https://user-images.githubusercontent.com/17715408/90207153-1d471300-de18-11ea-870c-b3690f32ac9d.png)
![image](https://user-images.githubusercontent.com/17715408/90207163-23d58a80-de18-11ea-9fcf-2df9931c85f9.png)
![image](https://user-images.githubusercontent.com/17715408/90207171-2a640200-de18-11ea-8c32-47fc140d9e46.png)
![image](https://user-images.githubusercontent.com/17715408/90207190-33ed6a00-de18-11ea-9fc0-678681687571.png)

**Comment by wumingman** [comment]
大佬，有空的话，辛苦，把信息流和插屏的先支持个性化模板呗，现在穿山甲后台创建广告位，除了开屏广告位，其他的我这边都只能创建个性化模板广告，没得选

**Comment by nullptrX** [comment]
banner不是支持了吗，你赋值isExpress=true了吗？

**Comment by wumingman** [comment]
banner 是可以啦！我的标题已经把Banner 排除在外了

**Comment by nullptrX** [comment]
插屏还不行吗？我昨天创建了一个模版渲染的可以用的。
信息流今天可以搞定，其他的暂时没时间弄了。

**Comment by wumingman** [comment]
感谢大佬的分享，我刚试了插屏的也可以，是我把InterstitialId的值弄错了，如果大佬后期把激励视频也支持自定义渲染广告位，烦请通知Flutter小白的我一声，不胜感激

**Comment by nullptrX** [comment]
模版渲染支持：
- [x] Banner
- [x] Feed
- [x] Interstitial
- [ ] Rewarded Video
- [ ] Fullscreen Video

```dart
dependencies:
  pangle_flutter: ^0.1.3
```

**Comment by nullptrX** [comment]
@wumingman 激励视频已支持模板渲染

**Comment by wumingman** [comment]
> @wumingman 激励视频已支持模板渲染

感谢大佬开源，辛苦啦

**Comment by nullptrX** [comment]
还有什么建议吗

**Comment by LeslieChan66** [comment]
sofa
