### ISSUE TITLE
the SDK package is incomplete. It is recommended to verify the integrity of SDK package or contact technical support.

### ISSUE THREAD

**Issue by badboy-tian** [nullptrX/pangle_flutter#50]
**1.简述问题**
sdk报错: the SDK package is incomplete. It is recommended to verify the integrity of SDK package or contact technical support.

**2.重现步骤**

**3.期望结果**

**4.SDK版本:**
 - flutter:2.5.1
 - dart:
 - pangle_flutter:1.2.0
 - android:
 - iOS:14.4.2

**额外信息**
无

**Comment by nullptrX** [comment]
用1.4.4试试。另外简述问题，不是贴错误信息。是怎么发生的？后续继续类似这样的问题一律忽略。
