### ISSUE TITLE
iOS使用 SplashView 限制不了宽高

### ISSUE THREAD

**Issue by 50431040** [nullptrX/pangle_flutter#51]
**1.简述问题**
iOS上使用SplashView，是全屏显示的，无法限制宽高。用示例项目测试也是如此。Android是正常的。

**2.重现步骤**

**3.期望结果**
iOS上使用SplashView，可以限制宽高。

**4.SDK版本:**
 - flutter: 2.0.0
 - dart: 2.12
 - pangle_flutter: 1.4.4
 - android: 
 - iOS: 14.5

**额外信息**
无

**Comment by nullptrX** [comment]
不能限制宽高是怎么回事呢？贴出你的部分代码看看吧

**Comment by nullptrX** [comment]
的确是这样，我以前的版本还是正常的。可能跟升级sdk有关系。我优化一下。
