### ISSUE TITLE
ios 插屏广告空白

### ISSUE THREAD

**Issue by zhanchi88** [nullptrX/pangle_flutter#52]
**1.简述问题**
苹果7,插屏广告显示空白没有图片，标题正常显示，点击广告也正常跳转

**2.重现步骤**
每次调用插屏广告都会出现

**3.期望结果**
修复

**4.SDK版本:**
 - flutter: 2.2.3
 - dart:
 - pangle_flutter: 1.4.4
 - android: 
 - iOS: 苹果7 软件版本12.4.1

**额外信息**
无

**Comment by nullptrX** [comment]
广告位上线了吗？
