### ISSUE TITLE
Feed Express Ad信息流广告视频元素残留

### ISSUE THREAD

**Issue by alexjie** [nullptrX/pangle_flutter#57]
**1.简述问题**
Feed Express Ad信息流广告，如果内部是视频类广告的话，当用户切换路由时，视频元素仍旧残留在用户界面上

**2.重现步骤**
1、使用最新版本1.4.4，编译example内demo
2、依次点击 Express AD -> Feed Express AD  等待列表渲染
3、如果信息流中显示的是视频类广告，视频开始播放时，点击Dislike 跳转到新的路由

**3.期望结果**
期望：界面上正在播放的视频类广告消失
实际：视频仍残留在界面上

**4.SDK版本:**
 - flutter: 2.5.3
 - dart: 2.14.4
 - pangle_flutter: 1.4.4
 - android: 9
 - iOS: 

**额外信息**
无

**Comment by nullptrX** [comment]
如果是这样的话，我可以新建一个页面来显示视频，这样应该可以避免残留。

**Comment by nullptrX** [comment]
能否有录像看看？

**Comment by alexjie** [comment]
效果如下面视频链接，切换route后，上一页的视频广告会出现在下一个路由上

https://user-images.githubusercontent.com/7931166/139969682-2d6c77a4-280d-4a26-a746-0a9efb485d6e.mov

**Comment by alexjie** [comment]
测试了如下5款android手机：
1、三星 android 8 无问题
2、三星 android 9 必现
3、vivo android 9 必现
4、oppo android 11 必现
5、huawei harmony 2.0 无问题
感觉是android 9以上都有问题。

**Comment by nullptrX** [comment]
```dart
await pangle.init(
    android: AndroidConfig(
        useTextureView: true,    
  );
```

这个设置为true试试。

**Comment by alexjie** [comment]
没注意到这个参数，的确有效，感谢🙏

**Comment by nullptrX** [comment]
有用户遇到useTextureView=true时，视频广告无法播放。useTextureView=false(SurfaceView)时就可以播放了。如果是这样的话，建议针对不同的机型配置这个属性的值。比如高于Android 9设置为true，低于则设置为false。仅供参考。
