### ISSUE TITLE
初始化参数错误

### ISSUE THREAD

**Issue by lianfanghua** [nullptrX/pangle_flutter#58]
**1.简述问题**
![image](https://user-images.githubusercontent.com/12154736/138692455-f9d13862-28e7-4343-9a70-04e2a5ab511c.png)
ios代码上init参数中isPaidApp的取值似乎是错的（如图）

**Comment by lianfanghua** [comment]
> 看文档的确是错误的，应该是UInt类型
> 
> https://www.csjplatform.com/union/media/union/download/detail?id=16&docId=5de8d570b1afac00129330c8&osType=ios#coppa%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E
> 
> 
> 
> + (void)setCoppa:(NSUInteger)Coppa;

我想表达的不是类型错误，而是key取错了，这里取的应该是isPaidApp，而不是coppa

**Comment by nullptrX** [comment]
感谢提醒
