### ISSUE TITLE
可以配置同时支持海内与海外吗？

### ISSUE THREAD

**Issue by kimmy214** [nullptrX/pangle_flutter#59]
**1.简述问题**

可以配置同时支持海内与海外吗？

**Comment by nullptrX** [comment]
具体什么需求能说说吗？

**Comment by realkimmy** [comment]
> 具体什么需求能说说吗？

我有一些应用同时在国内和国外上架了

**Comment by nullptrX** [comment]
国外的话 iOS的sdk是在这里面可以配置的。安卓的sdk由于sdk变动，不方便适配，就剔除了。如果你懂安卓的话，可以把国外sdk导入进来自己适配。国外的只是比国内的少一些回调和配置，大体不变。
