### ISSUE TITLE
not find compatible versions for pod "Bytedance-UnionAD"

### ISSUE THREAD

**Issue by LuYinhao** [nullptrX/pangle_flutter#6]
flutter编译运行的时候pods报错：

[!] CocoaPods could not find compatible versions for pod "Bytedance-UnionAD":
  In Podfile:
    pangle_flutter (from `.symlinks/plugins/pangle_flutter/ios`) was resolved to 0.1.11, which depends on
      Bytedance-UnionAD (~> 3.2.0.1)

Specs satisfying the `Bytedance-UnionAD (~> 3.2.0.1)` dependency were found, but they required a higher minimum deployment target.

**Comment by nullptrX** [comment]
Bytedance-UnionAD最低支持9.0
根据提示，在iOS项目下的Podfile开头增加这一句

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
```
