### ISSUE TITLE
激励视频如何跳过呢？

### ISSUE THREAD

**Issue by zeewell** [nullptrX/pangle_flutter#66]
App在好几个Android应用市场上架被拒绝，因为激励视频无法跳过。不知道这个如何处理？看穿山甲后台，也没有看到有相关的配置项。

**Comment by nullptrX** [comment]
激励视频应该不能跳过，全屏视频才有。

**Comment by zeewell** [comment]
解决了。提交工单，联系客服申请开通。。。
