### ISSUE TITLE
example中找不到podfile文件？

### ISSUE THREAD

**Issue by bigtotorouk** [nullptrX/pangle_flutter#67]
**1.简述问题**
objc[44845]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x2084e6c10) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1149082b8). One of the two will be used. Which one is undefined.
    objc[44845]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x2084e6c60) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x114908308). One of the two will be used. Which one is undefined.
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/xxxxx/soft-install/flutter/.pub-cache/hosted/pub.flutter-io.cn/pangle_flutter-1.4.6/ios/Classes/FLTSplashView.swift:83:53: error: cannot convert value of type 'CGFloat' to expected argument type 'Double'
            let width = expressArgs["width"] ?? uiframe.width
                                                        ^
                                                Double(      )
    /Users/xxxx/soft-install/flutter/.pub-cache/hosted/pub.flutter-io.cn/pangle_flutter-1.4.6/ios/Classes/FLTSplashView.swift:84:55: error: cannot convert value of type 'CGFloat' to expected argument type 'Double'
运行报错。 

我集成到ios中，测试开屏广告。 程序无法跑起来。出现上述问题。 我已按照穿山甲xcode的基本设置了 。 我的电脑是m1. pod的安装方式：
arch -x86_64 pod install --repo-update

**4.SDK版本:**
 - flutter: 2.5
 - dart:2.14
 - pangle_flutter:1.4.6
 - android:
 - iOS:

**Comment by bigtotorouk** [comment]
it does not to be solved.

**Comment by nullptrX** [comment]
请问swift版本是多少的？

**Comment by bigtotorouk** [comment]
> 请问swift版本是多少的？

swift 5

**Comment by nullptrX** [comment]
试试新版本
