### ISSUE TITLE
打印日志问题

### ISSUE THREAD

**Issue by nnianhou-** [nullptrX/pangle_flutter#7]
为啥运行一直打印这个日志，疯狂打印，这有影响吗？我运行你demo也是这样。我关闭打印日志也不行

E/SQLiteDatabase(30445): android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: trackurl.id (code 2067 SQLITE_CONSTRAINT_UNIQUE)
E/SQLiteDatabase(30445): 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
E/SQLiteDatabase(30445): 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:883)
E/SQLiteDatabase(30445): 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
E/SQLiteDatabase(30445): 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
E/SQLiteDatabase(30445): 	at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1663)
E/SQLiteDatabase(30445): 	at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1532)
E/SQLiteDatabase(30445): 	at com.bytedance.sdk.openadsdk.core.g$c.a(DBHelper.java:127)
E/SQLiteDatabase(30445): 	at com.bytedance.sdk.openadsdk.multipro.a.b.a(DBMultiProviderImpl.java:136)
E/SQLiteDatabase(30445): 	at com.bytedance.sdk.openadsdk.multipro.f.a(TTProviderManager.java:166)
E/SQLiteDatabase(30445): 	at com.bytedance.sdk.openadsdk.multipro.TTMultiProvider.insert(TTMultiProvider.java:50)
E/SQLiteDatabase(30445): 	at android.content.ContentProvider.insert(ContentProvider.java:1645)
E/SQLiteDatabase(30445): 	at android.content.ContentProvider$Transport.insert(ContentProvider.java:330)
E/SQLiteDatabase(30445): 	at android.content.ContentResolver.insert(ContentResolver.java:2045)
E/SQLiteDatabase(30445): 	at android.content.ContentResolver.insert(ContentResolver.java:2007)
E/SQLiteDatabase(30445): 	at com.bytedance.sdk.openadsdk.multipro.a.a.a(DBMultiAdapter.java:41)
E/SQLiteDatabase(30445): 	at com.bytedance.sdk.openadsdk.l.g.a(TrackRetryRepertoryImpl.java:61)
E/SQLiteDatabase(30445): 	at com.bytedance.sdk.openadsdk.l.b$a.a(TrackAdUrlImpl.java:168)
E/SQLiteDatabase(30445): 	at com.bytedance.sdk.openadsdk.l.b$a.doInBackground(TrackAdUrlImpl.java:98)
E/SQLiteDatabase(30445): 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
E/SQLiteDatabase(30445): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/SQLiteDatabase(30445): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/SQLiteDatabase(30445): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/SQLiteDatabase(30445): 	at java.lang.Thread.run(Thread.java:923)
D/DBMultiProviderImpl(30445): insert: content://io.github.nullptrx.pangleflutterexample.TTMultiProvider/t_db/ttopensdk.db/trackurl
E/SQLiteDatabase(30445): Error inserting id=e1d1f8bc-63c7-4cc2-8570-8596070c2556_1599122746976 url=https://adsmis.duxiaoman.com/adsmis/api/toutiaomonitor?state=-1&cid=1674796367471630&adid=1674724351572012&mac=a2f3168fa6d0c8a1d701bc52734c2fff&idfa=&imei=&mac1=__MAC1__&aaid=__AAID__&androidid=&duid=__DUID__&udid=&lbs=0.000000x-0.000000x100.0&os=0&ip=171.44.171.43&timestamp=1599122685000&callback_url=http%3A%2F%2Fad.toutiao.com%2Ftrack%2Factivate%2F%3Fcallback%3DCKzwybDy5PwCEI7It9T-5vwCGOfeoNbQ9NsEIOfeoNbQ9NsEKIPQpc_GsPwCMA44lPHmwgNCKTM4ZGU0MzkyLWZkZmMtNDNjMy1hNGJhLTljMzg3NTk3NzAyYnUzOTU3SIDSk60DUABoiICK5OXRq6RfcIiAieTl0aukX3iN4OSfnMb7AoABs-Cmyunk_AI%3D%26os%3D0%26muid%3D&ad_name=wcErlE5O1599-%E7%B3%BB%E7%BB%9F-%E6%A8%AA%E7%89%88%E8%A7%86%E9%A2%91-%E6%B2%99%E5%8F%91%E5%AE%A2%E6%9C%8D-%E7%A9%BF%E5%B1%B1%E7%94%B2-%E9%80%9A%E6%8A%95-0811-%E6%89%8B%E5%8A%A8%E5%87%BA%E4%BB%B7-%E5%85%A8%E9%93%BE%E8%B7%AF&csite=900000000&ctype=5&ua=Mozilla%2F5.0+%28Linux%3B+Android+10%3B+Build%2FRPP2.200227.014.A1%3B+wv%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Version%2F4.0+Chrome%2F82.0.4062.3+Mobile+Safari%2F537.36&click_id=__CLICK_ID__&convert_id=__CONVERT_ID__&callback_param=CKzwybDy5PwCEI7It9T-5vwCGOfeoNbQ9NsEIOfeoNbQ9NsEKIPQpc_GsPwCMA44lPHmwgNCKTM4ZGU0MzkyLWZkZmMtNDNjMy1hNGJhLTljMzg3NTk3NzAyYnUzOTU3SIDSk60DUABoiICK5OXRq6RfcIiAieTl0aukX3iN4OSfnMb7AoABs-Cmyunk_AI=&req_id=38de4392-fdfc-43c3-a4ba-9c387597702bu3957&oaid=&cid_name=&campaign_id=1674721989603379&campaign_name=%E7%A9%BF%E5%B1%B1%E7%94%B2%E5%AF%B9%E7%85%A7%E7%BB%840811&request_id=38de4392-fdfc-43c3-a4ba-9c387597702bu3957&geo=__GEO__&model= retry=5 replaceholder=1
E/SQLiteDatabase(30445): android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: trackurl.id (code 2067 SQLITE_CONSTRAINT_UNIQUE)
E/SQLiteDatabase(30445): 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
E/SQLiteDatabase(30445): 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:883)
E/SQLiteDatabase(30445): 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
E/SQLiteDatabase(30445): 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
E/SQLiteDatabase(30445): 	at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1663)
E/SQLiteDatabase(30445): 	at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1532)
E/SQLiteDatabase(30445): 	at com.bytedance.sdk.openadsdk.core.g$c.a(DBHelper.java:127)
E/SQLiteDatabase(30445): 	at com.bytedance.sdk.openadsdk.multipro.a.b.a(DBMultiProviderImpl.java:136)
E/SQLiteDatabase(30445): 	at com.bytedance.sdk.openadsdk.multipro.f.a(TTProviderManager.java:166)
E/SQLiteDatabase(30445): 	at com.bytedance.sdk.openadsdk.multipro.TTMultiProvider.insert(TTMultiProvider.java:50)
E/SQLiteDatabase(30445): 	at android.content.ContentProvider.insert(ContentProvider.java:1645)
E/SQLiteDatabase(30445): 	at android.content.ContentProvider$Transport.insert(ContentProvider.java:330)
E/SQLiteDatabase(30445): 	at android.content.ContentResolver.insert(ContentResolver.java:2045)
E/SQLiteDatabase(30445): 	at android.content.ContentResolver.insert(ContentResolver.java:2007)
E/SQLiteDatabase(30445): 	at com.bytedance.sdk.openadsdk.multipro.a.a.a(DBMultiAdapter.java:41)
E/SQLiteDatabase(30445): 	at com.bytedance.sdk.openadsdk.l.g.a(TrackRetryRepertoryImpl.java:61)
E/SQLiteDatabase(30445): 	at com.bytedance.sdk.openadsdk.l.b$a.a(TrackAdUrlImpl.java:168)
E/SQLiteDatabase(30445): 	at com.bytedance.sdk.openadsdk.l.b$a.doInBackground(TrackAdUrlImpl.java:98)
E/SQLiteDatabase(30445): 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
E/SQLiteDatabase(30445): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/SQLiteDatabase(30445): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/SQLiteDatabase(30445): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/SQLiteDatabase(30445): 	at java.lang.Thread.run(Thread.java:923)
Application finished.

**Comment by nullptrX** [comment]
是sdk打印的，我也没办法

**Comment by nnianhou-** [comment]
> 是sdk打印的，我也没办法

这个日志疯狂打印个不停，集成后没法调试其他东西，你们怎么处理的？刚接触flutter不久。

**Comment by nullptrX** [comment]
> > 是sdk打印的，我也没办法
> 
> 这个日志疯狂打印个不停，集成后没法调试其他东西，你们怎么处理的？刚接触flutter不久。

你知道什么情况会打印吗？

**Comment by nullptrX** [comment]
[`android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: trackurl.id (code 2067 SQLITE_CONSTRAINT_UNIQUE)`](https://blog.csdn.net/wwzqj/article/details/7801702)

问题出在`TTMultiProvider`上。重复插入相同键。
`path`: `databases/ttopensdk.db/trackurl`

**Comment by nullptrX** [comment]
跟踪了一下调用栈，`com.bytedance.sdk.openadsdk.utils.y#a()`，该方法获取devOaid时，因为我的sdk时kotlin实现的，见下代码。异常最终跳到了`com.bytedance.sdk.openadsdk.l.b.a#a(java.lang.Void...)`，该方法中catch (Throwable var7) 异常未打印，是我这边kotlin返回类型问题，最后却导致了open_ad_sdk流程走不通。
```kotlin
customController(object : TTCustomController() {
    override fun isCanUseLocation(): Boolean {

        return isCanUseLocation ?: true
    }

    override fun isCanUsePhoneState(): Boolean {
        return isCanUsePhoneState ?: true
    }

    override fun isCanUseWriteExternal(): Boolean {
        return isCanUseWriteExternal ?: true
    }

    override fun isCanUseWifiState(): Boolean {
        return isCanUseWifiState ?: true
    }

    override fun getDevImei(): String? {
        return devImei
    }

    override fun getTTLocation(): TTLocation? {
        return ttLocation
    }

    // 返回类型之前为String, sdk报错时吞掉了我的异常
    override fun getDevOaid(): String? { 
        return devOaid?:super.getDevOaid()
    }
})
```

**Comment by nullptrX** [comment]
使用`pangle_flutter: ^0.3.1`已修复
