### ISSUE TITLE
「开屏」广告的「请求量」远远大于「展现量」的问题

### ISSUE THREAD

**Issue by zeewell** [nullptrX/pangle_flutter#70]
**1.简述问题**
看穿山甲后台数据，发现「开屏」广告的「请求量」远远大于「展现量」，是因为默认有「预加载」吗？

**3.期望结果**
两者数据越接近越好，或者是否能够有相关的参数可以配置？就像插屏广告那样可以选择预加载或者别的。

**Comment by nullptrX** [comment]
开屏没有预加载呀

**Comment by zeewell** [comment]
那好奇怪，估计 穿山甲 SDK 自己的问题。

**Comment by nullptrX** [comment]
你方便调试看看不嘛  SplashView里面的回调  看看请求了多少次

**Comment by zeewell** [comment]
好，我这两天看看。

**Comment by zeewell** [comment]
更新SDK后，好多了。估计是官方SDK那个（或几个）版本的问题。
