### ISSUE TITLE
点击广告下载后的通知栏消息栏无法关闭（华为审核时被拒绝）

### ISSUE THREAD

**Issue by zeewell** [nullptrX/pangle_flutter#71]
华为审核时被拒绝：

> 详细描述：我们发现您的应用无法关闭通知栏消息，请勿使用FLAG_ONGOING_EVENT、FLAG_NO_CLEAR标识，或者调用NotificationBuilder.setOngoing(true)方法。请参考《审核指南》第3.3相关审核要求：https://developer.huawei.com/consumer/cn/doc/50104

请教，这个怎么处理呢？

**Comment by nullptrX** [comment]
什么广告的通知消息呢

**Comment by zeewell** [comment]
点击广告后，在下载App时会有一个通知，左滑无法关闭。如图里的「拼多多」就是广告下载的App，这个通知栏样式就无法关闭：

![image](https://user-images.githubusercontent.com/1610404/145930321-0f40a289-fff7-47c3-8711-04889f10ea5a.png)

**Comment by nullptrX** [comment]
`allowShowNotify` 初始化的时候把这个置为false呢  直接不显示  好像只有这个属性可以配置
