### ISSUE TITLE
IOS广告整改

### ISSUE THREAD

**Issue by SinoMiles** [nullptrX/pangle_flutter#72]
![image](https://user-images.githubusercontent.com/9588025/146375787-0871a897-317a-47d6-a85c-da22355203ca.png)
现在的代码是进入页面初始化的时候直接调用，目前只使用开屏和激励视频广告
下面是图，第二个问题还可以理解，第一个违规是要怎么整改？有没有什么建议！

![image](https://user-images.githubusercontent.com/9588025/146376427-a98b9a20-3b0a-4724-a4ed-0bcb9ace533f.png)
![image](https://user-images.githubusercontent.com/9588025/146376446-13e03195-8892-45ad-8d46-f3bb0ecb2eb7.png)

```

/// 全屏类型
/// [kSplashId] 开屏广告ID, 对应Android的CodeId，对应iOS的slotID
await pangle.loadSplashAd(
  iOS: IOSSplashConfig(slotId: kSplashId, isExpress: false),
  android: AndroidSplashConfig(slotId: kSplashId, isExpress: false),
);

/// [kRewardedVideoId] 激励视频广告ID, 对应Android的CodeId，对应iOS的slotID
pangle.loadRewardVideoAd(
   iOS: IOSRewardedVideoConfig(slotId: kRewardedVideoId),
   android: AndroidRewardedVideoConfig(slotId: kRewardedVideoId),
 );
```

**Comment by nullptrX** [comment]
不是有显示logo吗

**Comment by SinoMiles** [comment]
但是收到邮件说没，所以也不懂啥情况。

**Comment by nullptrX** [comment]
那就不太清楚了  我好久没用了诶
