### ISSUE TITLE
iOS接入1.5.0+1版本报错

### ISSUE THREAD

**Issue by LuodiJackShen** [nullptrX/pangle_flutter#76]
**1.简述问题**
项目中接入1.5.0+1版本，直接报错，主要是找不到几个类，可以看下额外信息的图片。

**2.重现步骤**

**3.期望结果**

**4.SDK版本:**
 - flutter:  2.10.2
 - dart: 2.16.1
 - pangle_flutter: 1.5.0+1
 - android:
 - iOS: 15.2

**额外信息**
<img width="1076" alt="截屏2022-03-09 21 00 38" src="https://user-images.githubusercontent.com/25525335/157447091-39c65ac1-71f3-4fbb-9efe-86b2d14af433.png">

**Comment by zeewell** [comment]
Ads-CN 4.3 版本目前还没适配。可以先用：4.2.5.6 版本

@nullptrX

**Comment by nullptrX** [comment]
我记得我在podspec里面指定的是4.2+的版本  不会用到4.3的

**Comment by zeewell** [comment]
@nullptrX 嗯，默认没问题的。

估计是 @LuodiJackShen 在 ios 目录里执行了 `pod update`，这个操作的话，这里的版本限制就没有用了（没去细究，应该是这么回事）

**Comment by LuodiJackShen** [comment]
> 

是的，执行了pod update命令

**Comment by LuodiJackShen** [comment]
该怎么解决呢？

**Comment by nullptrX** [comment]
只要没改 应该只会拉到4.2的版本, 我晚点适配一下
