### ISSUE TITLE
1.5.0+1是否支持海外sdk

### ISSUE THREAD

**Issue by fuufuuf** [nullptrX/pangle_flutter#77]
**1.简述问题**
新版本的build.gradle使用的是国内的sdk,怎样切成海外的sdk, com.pangle.global:ads-sdk:4.1.1.2。
dependencies {
    api 'com.pangle.cn:ads-sdk-pro:[4.2,4.3)'
    implementation 'androidx.appcompat:appcompat:[1.3,1.4)'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

**2.重现步骤**

**3.期望结果**

**4.SDK版本:**
 - flutter: 2.10.2
 - dart: 2.16.1
 - pangle_flutter: 1.5.0
 - android:
 - iOS:

**额外信息**
无

**Comment by nullptrX** [comment]
海外版本改动不大  只是少了一些回调  有能力的话  可以fork下来改改

**Comment by fuufuuf** [comment]
我能从某一个版本folk吗，请问是从哪个版本开始不支持海外版本了

**Comment by nullptrX** [comment]
v1.1.0之后去除的。其实可以照现在版本改，你看哪里报错再对应改。
