### ISSUE TITLE
 Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:[1.3.40,1.6.10].

### ISSUE THREAD

**Issue by jameswanliu** [nullptrX/pangle_flutter#81]
**1.简述问题**

**2.重现步骤**

**3.期望结果**

**4.SDK版本:**
 - flutter:
 - dart:
 - pangle_flutter:
 - android:
 - iOS:

**额外信息**

- [ ] [ Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:[1.3.40,1.6.10].](![D10B8214-EB8C-4fdd-8130-AEFF20704FE4](https://user-images.githubusercontent.com/7357320/160316781-6e55d376-9ad7-41b5-856e-a2552d0be084.png))

     Required by:
         project :pangle_flutter
      > Failed to list versions for org.jetbrains.kotlin:kotlin-gradle-plugin.
         > Unable to load Maven meta-data from https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/maven-metadata.xml.
            > Could not HEAD []('https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/maven-metadata.xml'.)
[无[](url)](url)

**Comment by nullptrX** [comment]
可以打开的
