### ISSUE TITLE
为什么海外的广告位id显示40006错误码

### ISSUE THREAD

**Issue by korolzhang** [nullptrX/pangle_flutter#83]
**1.简述问题**

**2.重现步骤**

**3.期望结果**

**4.SDK版本:**
 - flutter:
 - dart:
 - pangle_flutter:
 - android:
 - iOS:

**额外信息**
无

**Comment by korolzhang** [comment]
海外的appID初始化成功
{"code":0,"message":""}
下一步进行海外id的初始化：
_loadFeedAd() async {
    var expressSize = PangleExpressSize.aspectRatio(375 / 284);
    PangleAd feedAd = await pangle.loadFeedAd(
      android: AndroidFeedConfig(
        slotId: '980132524',
        expressSize: expressSize,
        // slotId: kFeedId,
      ),
    );
    print('feedAd==>${feedAd.code}');
  }
显示错误码40006

**Comment by nullptrX** [comment]
自行查询错误码，[错误码列表](https://www.csjplatform.com/supportcenter/5421)
