### ISSUE TITLE
iOS SDK 发布了 4.7和4.8 改动不小，有计划支持吗？

### ISSUE THREAD

**Issue by zeewell** [nullptrX/pangle_flutter#86]
当前不支持 iOS SDK 4.7和4.8 版本，近期有计划支持吗？

**Comment by nullptrX** [comment]
好的  我这两天看看

**Comment by zeewell** [comment]
4.8 的更新还是很重要的：

【修复】已知问题；
【兼容】Xcode14+iOS16开发环境；
【新增】手动集成导入时，新增DeviceCheck.framework依赖；


@nullptrX  期待适配！

**Comment by zeewell** [comment]
我现在是几个广告商的SDK，按点击率、收益情况等计算显示几率。

gromore 能接入当然就太好了！应该能我我上面的方法收益高些哈哈～

对了， #87 这个如果可能合并下或者你直接看着改掉哈，不然编译过不了了
