### ISSUE TITLE
Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk7:[1.3.40,1.6.10]

### ISSUE THREAD

**Issue by hangzhi22** [nullptrx/pangle_flutter#90]
**1.简述问题**
Execution failed for task ':pangle_flutter:mergeReleaseResources'.
> Could not resolve all files for configuration ':pangle_flutter:releaseRuntimeClasspath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk7:[1.3.40,1.6.10].

**2.重现步骤**

**3.期望结果**
buildscript {
    ext.kotlin_version = '[1.3.2, 1.6.0]' ->  ext.kotlin_version = '1.6.0'

**4.SDK版本:**
 - flutter: 3.0
 - dart: 
 - pangle_flutter: 2.40
 - android:
 - iOS:

**额外信息**
目前我手动改，绕过这个问题。

**Comment by nullptrx** [comment]
Latest version is `1.9.7`, not `2.40`.
