### ISSUE TITLE
Specifying subspec(global) in Podfile is not working.

### ISSUE THREAD

**Issue by krgpi** [nullptrx/pangle_flutter#91]
**1.简述问题**
I want to use pangle global, so I specified subspec to global as written in Readme.md.
After `pod install`, `flutter run` will fail with error below. 

<img width="582" alt="image" src="https://user-images.githubusercontent.com/17940589/198955748-991c01b5-37d5-433c-a1e2-ac116f1988c9.png">

**2.重现步骤**
In ios/Podfile, choose global. 
```ruby
      if plugin_name == 'pangle_flutter'
        # cn表示国内，global表示海外
        pod 'pangle_flutter/global', :path => File.join('.symlinks', 'plugins', plugin_name, 'ios')
      else
        pod plugin_name, :path => File.join('.symlinks', 'plugins', plugin_name, 'ios')
      end
```      

Then build flutter project to iOS Simulator.
You will see an error like below.
```bash
ios/Runner/GeneratedPluginRegistrant.m:162:9: fatal error: module 'pangle_flutter' not found
    @import pangle_flutter;
     ~~~~~~~^~~~~~~~~~~~~~
```

**3.期望结果**
Build successfully.

**4.SDK版本:**
 - flutter: 3.3.5
 - dart: 2.18.2
 - pangle_flutter: 1.9.7
 - android:
 - iOS:

**额外信息**
If I add some changes, it works. But I don't think this is not right way.
1. In Podfile, specify the pod name equal to flutter package name.

```ruby
      if plugin_name == 'pangle_flutter'
        # cn表示国内，global表示海外
        pod 'pangle_flutter', :path => File.join('.symlinks', 'plugins', plugin_name, 'ios')
      else
        pod plugin_name, :path => File.join('.symlinks', 'plugins', plugin_name, 'ios')
      end
```      
But, this will install pangle CN, so,

2. In pangle_flutter.podspec, change default subspec to global.
```ruby
  s.default_subspec   = 'global'
```

It seems your library works with CN, but not with global. Please provide correct way to switch CN and global or if there is correct way and I have some mistakes, please inform me.

**Comment by nullptrx** [comment]
pod 'pangle_flutter/global', :path => File.join('.symlinks', 'plugins', plugin_name, 'ios')

**Comment by nullptrx** [comment]
Do you try `pod update`?

**Comment by krgpi** [comment]
@nullptrx Yes, I've tried pod update. But this issue couldn't be resolved.

**Comment by nullptrx** [comment]
The overseas SDK functions have been removed.
