### ISSUE TITLE
ios splash 开屏加载方法无回调

### ISSUE THREAD

**Issue by xypmhxy** [nullptrx/pangle_flutter#93]
**1.简述问题**
ios 开屏广告采用默认模式关闭广告后没有返回，即loadSplashAd方法无返回一直等待
**2.重现步骤**
直接使用即可

**3.期望结果**
广告关闭后返回结果

**4.SDK版本:**
 - flutter:3.3.3
 - dart:
 - pangle_flutter:1.9.7
 - android:
 - iOS:16.1.1

**额外信息**
FLTSplashAd中splashAdDidClose增加一个回调
方法
 func splashAdDidClose(_ splashAd: BUSplashAd, closeType: BUSplashAdCloseType) {
        self.success?("close")
        splashAd.removeSplashView()
    }
![WX20221120-133023@2x](https://user-images.githubusercontent.com/26452957/202887200-343aa8a4-f8c2-44fc-ae19-7a143ff2bd0b.png)

**Comment by nullptrx** [comment]
Fixed at v2.0.0.
