### ISSUE TITLE
About 40006 Error

### ISSUE THREAD

**Issue by kkjk1176** [nullptrx/pangle_flutter#96]
Testing for global targets.
You are using a test-only 'appID' and 'slotID'.
However, '40006 / Invalid Slot ID' is being returned.
I desperately need your help.

中文
测试全球目标
您正在使用仅供测试的“appID”和“slotID”。
但是，返回“40006 / 无效插槽 ID”。
我迫切需要你的帮助。

iOS ==> `flutter: _pangleResult : 40006 / data analysis error / null`
AOS ==> `flutter: _pangleResult : 40006 / reason: 0  message: 广告位ID不合法 / null`

TestID : https://www.pangleglobal.com/integration/How-to-Test-Pangle-Ads-with-Ad-ID
ErrorCode : https://www.pangleglobal.com/kr/integration/error-code

---
 
 - flutter: 3.7.12 
 - dart: 2.19.6
 - pangle_flutter: ^1.9.7
 
 
**Main.dart**
```
void main() async {
 WidgetsFlutterBinding.ensureInitialized();
   await pangle.init(
    iOS: IOSConfig(appId: '8025677'),
    android: AndroidConfig(appId: '8025677'),
  );
```

**ShowAdsButton.dart**
```
onTap : (){
      PangleResult _pangleResult = await pangle.loadRewardedVideoAd(
                    iOS: IOSRewardedVideoConfig(slotId: '980088192'),
                    android: AndroidRewardedVideoConfig(slotId: '980088192'),
                  );
      
      print('_pangleResult : ${_pangleResult.code} / ${_pangleResult.message} / ${_pangleResult.verify}');
}
```

**Print Log**
iOS ==> `flutter: _pangleResult : 40006 / data analysis error / null`
AOS ==> `flutter: _pangleResult : 40006 / reason: 0  message: 广告位ID不合法 / null`

**Comment by zyw00** [comment]
您好 flutter 接入海外tt广告需要手动引入tt安卓的sdk吗

**Comment by nullptrx** [comment]
The overseas SDK functions have been removed.
